version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: talents
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d talents"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.backend
      args:
        HTTP_PROXY: "http://192.168.100.254:3128/"
        HTTPS_PROXY: "http://192.168.100.254:3128/"
    restart: always
    environment:
      DATABASE_URL: "postgresql://dev:dev123@db:5432/talents?schema=public"
      JWT_SECRET: "seu-secret-super-seguro-minimo-32-caracteres-aleat0ri0s"
      JWT_EXPIRES_IN: "7d"
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.frontend
      args:
        HTTP_PROXY: "http://192.168.100.254:3128/"
        HTTP_PROXY: "http://192.168.100.254:3128/"
        HTTPS_PROXY: "http://192.168.100.254:3128/"
        NEXT_PUBLIC_API_URL: "http://localhost:3001/api"
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001/api"
    depends_on:
      - backend
    ports:
      - "3000:3000"


volumes:
  pgdata:
